### PR TITLE
feat: support mqtts protocol

### LINKED ISSUE #141: Support secured protocols
#### Reason/Context
When specifying secured protocol and endpoints in the _server_ section, code generation fails with the following error:

> Something went wrong:
> Error: Server "production" uses the mqtts protocol but this template only supports the following ones: amqp,mqtt,kafka,kafka-secure,ws.
>     at isServerProtocolSupported (/Users/xxx/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/lib/templateConfigValidator.js:104:11)
>     at module.exports.validateTemplateConfig (/Users/xxx/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/lib/templateConfigValidator.js:26:5)
>     at Generator.generate (/Users/xxx/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/lib/generator.js:185:5)
>     at /Users/xxx/.nvm/versions/node/v14.16.1/lib/node_modules/@asyncapi/generator/cli.js:154:9
> 

In the asyncapi document, the server specification is as follows:

```
servers:
  production:
    url: "mqtts://xxx.yyy.cloud:8883"
    protocol: mqtts
```

Consider supporting the same protocols with security (TLS/SSL encrypted) - i.e., amqps, mqtts and wss.

This would help avoid manual updates to the common.yml file.

### PR DESCRIPTION
**Pull request by wandertaker**
**Description**

- Adds support for the MQTTS protocol
- Uses the same logic for MQTTS as for MQTT, as the underlying library can handle both protocols

**Related issue(s)**
Partially resolves #141 (only for secured MQTT)

### CODE REVIEW

**Review by derberg — CHANGES_REQUESTED** [review]
This is kick ass quality PR!!! Thanks @wandertaker 

I only want to ask for one improvement. Instead of adding completely new `mqtts` example for tests. I suggest you download https://raw.githubusercontent.com/asyncapi/spec/v2.2.0/examples/streetlights-mqtt.yml

and then:
- use it in `template integration tests for generated files using the generator and mqtt example` test instead of fetching it
- add another server to `servers`, like maybe `production-mqtts` so in your test you use the same asyncapi document but:
    ```
    const params = {
      server: 'production-mqtts'
    };
    ````


This way there is just one mqtt example for 2 different tests

**Comment by derberg** [comment]
@wandertaker nice, I never used `Jest Each` before, nifty! There is something failing, though, maybe you forgot to refresh snapshot?

**Comment by wandertaker** [comment]
@derberg should be fixed now.
On master, a few empty lines are needed that were missing in the snapshot.

**Comment by derberg** [comment]
@wandertaker there are some linter issues

sorry for being late this time but last week we had AsyncAPI Conf and it fully occupied me

**Comment by derberg** [comment]
@wandertaker oh cool 😄 thanks! so someone was watching after all 😄

**Review by derberg — APPROVED** [review]

**Comment by derberg** [comment]
Thanks a lot!

/rtm

**Comment by derberg** [comment]
@all-contributors please add @wandertaker for code,test

**Pull request merged**
