### PR TITLE
fix: log the name of the message if it is absent

### PR DESCRIPTION
**Pull request by ibishal**
**Description**
Added a param `messageRuntimeValidation`  which will log the messageId's if its missing and if false then it will not warn anything(by default it will be true)
Screenshot from 2024-07-02 02-18-41
image

image
image

**Related issue(s)**
#197

### CODE REVIEW

**Comment by ibishal** [comment]
> I'm only worried for those that do not care about validation, and cannot modify their documents to add identifiers, what in their case. We should probably allow to disable validation?

Hey @derberg i have not added this feature, we need to make changes in  `asyncapi/generator ` for it right ?

**Comment by derberg** [comment]
@ibishal no need to add anything to generator.

You simply need to introduce "parameter" feature. So let's say it is called `messageRuntimeValidation` that by default is set to `true`. If set to true, we add in generated code message validation code, and we also console log info that some message identifiers are missing. And we also need to log "that if you are not able to modify your asyncapi document to add missing IDs, then disable runtime validation logic by passing parameter messageRuntimeValidation set to false"

makes sense?

**Comment by ibishal** [comment]
Done @derberg

**Review by derberg — CHANGES_REQUESTED** [review]
I don't think you tested it manually as just looking at the code I see it errors.

you always have to check manually or at least have a good coverage of integration tests

the basic thing that I see is missing:
- `messageRuntimeValidation` parameter is not added to package.json to generator config
- no info in readme
-

**Comment by ibishal** [comment]
> I don't think you tested it manually as just looking at the code I see it errors.
 I have done manual testing for it. you can see it in the sc of pr description


>     * `messageRuntimeValidation` parameter is not added to package.json to generator config
It was added in the parameter of generator config in package.json

>     * no info in readme
will add it

**Comment by ibishal** [comment]
Do we need integration test here @derberg

**Comment by derberg** [comment]
I think I mixed the issues scope :( 

in general idea was that best DX is that user gets a feedback during generation, and not once the template is generated and code build and running

sorry but instead of parameter I think we need `generate:before` that will do it -> https://www.asyncapi.com/docs/tools/generator/hooks

wdyt?

**Comment by derberg** [comment]
closing, no further activity from the contributor

**Comment by ibishal** [comment]
@derberg, sorry from my side 

i want to finish it, can we open this?

**Comment by derberg** [comment]
just reopen new PR but updated according to previous feedback

**Pull request closed without merging**
